### ISSUE TITLE
Copilot Chat 并不是调用的GPT4，而是GPT3。那copilot-gpt4-service受到这个影响吗？

### ISSUE THREAD

**Issue by Etleventt** [aaamoon/copilot-gpt4-service#211]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/56229241/2b7d2565-2e1d-4f2a-ab26-31175856e3b0)

**Comment by Mark7888** [comment]
(I don't speak chinise, so I could only translate the title.)

If you're asking, why does copilot says, it is GPT-3, here is a link to the same question on the openai forum:
https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881/2

**Comment by thangckt** [comment]
I have a related problem [in this issue](https://github.com/aaamoon/copilot-gpt4-service/issues/189#issuecomment-1897981772)

**Comment by aaamoon** [comment]
By default, Copilot Chat automatically switches between GPT-3.5 and GPT-4 models, if you use VS Code, you can add the following configuration to the settings.json to force Copilot Chat to ask all questions and go to GPT-4 models

````
"github.copilot.advanced": {
    "debug.overrideChatEngine": "gpt-4"
}
````

**Comment by AielloChan** [comment]
### ChatGPT web 3.5 turbo
<img width="785" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/7900765/7b6909ec-873b-409d-a79b-b82fa38faf43">

Q: 树上 9 只鸟，打掉一只还有几只？There are 9 birds in the tree. If you kill one, how many will remain?

A: 如果打掉一只鸟，其他的鸟可能会被吓飞走，所以树上可能不再有鸟。如果假设其他鸟不被吓飞走，那么树上就没有鸟了。If you kill one bird, the others may be frightened away, so there may no longer be birds in the tree. If we assume that other birds are not frightened and fly away, then there are no birds in the tree.


### copilot-gpt4-service
<img width="898" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/7900765/40c0e38c-2fe2-419d-b493-cbf92cccf2e2">

Q: 树上 9 只鸟，打掉一只还有几只？There are 9 birds in the tree. If you kill one, how many will remain?

A: 打掉一只鸟后，树上还剩下8只鸟。After killing one bird, there are 8 birds left in the tree.


Seems that the model used by copilot will be dumber than free ChatGPT web one 🥲

**Comment by thangckt** [comment]
This is from my site
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/46436648/3b21f3e3-5794-4006-8155-ff77b318653e)

**Comment by S-H-Go** [comment]
@AielloChan 
Q: 树上 9 只鸟，打掉一只还有几只？There are 9 birds in the tree. If you kill one, how many will remain?
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/73683678/d938493b-bdc3-410a-9a0c-901cbb436593)
A: 打掉一只鸟后，树上还剩下8只鸟。After one bird is knocked off, there are eight birds left in the tree.

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/73683678/00e9368e-1057-4c5c-986d-9c6b00b83316)
A: 树上如果原来有9只鸟，打掉一只后，其他的鸟可能会因为声响吓飞，所以理论上树上不会再有鸟了。但如果我们只考虑数学上的简单减法，那么9减去1等于8，所以会剩下8只鸟。但实际情况取决于鸟的行为反应。If there were originally 9 birds on the tree, after knocking out one, the others might fly away because of the sound scare, so theoretically there would be no more birds on the tree. But if we only consider simple subtraction in math, then 9 minus 1 equals 8, so there will be 8 birds left. But the reality depends on the behavioral response of the birds.

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/73683678/05a58ef8-52e0-49d9-aa0b-70b356fc72ea)
A: 打掉一只鸟后，树上还剩下8只鸟。After one bird is knocked off, there are eight birds left in the tree.

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/73683678/a32189f3-0620-475b-b63e-79b69b64c732)
A: 这个问题可能有两种答案，取决于你的解读：

1. 如果你从纯数学的角度来看，那么答案是 8 只。因为 9 只鸟减去 1 只鸟等于 8 只鸟。

2. 如果你从实际的角度来看，那么答案可能是 0 只。因为当你打掉一只鸟时，其它的鸟可能会被吓飞，所以树上可能不再有鸟。

There are two possible answers to this question, depending on your interpretation:

1. if you look at it from a purely mathematical point of view, then the answer is 8 birds. If you look at it from a purely mathematical point of view, then the answer is 8. This is because 9 birds minus 1 bird equals 8 birds.

2. If you look at it from a practical point of view, then the answer is probably 0. This is because when you knock out one bird, the other birds may be scared off, so there may no longer be any birds in the tree.

也许只是你没有在 ChatGPTNextWeb 中切换 GPT 版本，在 ChatGPTNextWeb 中默认的 GPT 版本是 gpt-3.5-turbo ，你可以在设置中设置默认选项为 gpt-4 。Maybe it's just that you haven't switched the GPT version in ChatGPTNextWeb, the default GPT version in ChatGPTNextWeb is gpt-3.5-turbo, you can set the default option to gpt-4 in the settings.
